### PR TITLE
Add support for more formats

### LINKED ISSUE #1: Support other types and formats
Hey @Noamko. I'd like to contribute some code to support other types and formats like the ones shown below. Is QuickLaTeX still maintained such that the changes would make it to the Raycast store? I am asking as I would profit a lot from the new functionality.

CleanShot 2023-09-11 at 10 36 45@2x

### PR DESCRIPTION
**Pull request by marcjulianschwarz**
## Changes
- Adds support for PNG, GIF, SVG, EMF and PDF
- Use white font color to display LaTeX in dark mode
- Preferences for SVG width, height and viewbox
- LaTeX command argument

Closes #1 

CleanShot 2023-09-12 at 21 13 03@2x

### CODE REVIEW

**Comment by marcjulianschwarz** [comment]
Just noticed that the white font color currently applies when in light mode too. This is not correct, will fix it.

**Comment by marcjulianschwarz** [comment]
Fixed

CleanShot 2023-09-12 at 21 11 14@2x
CleanShot 2023-09-12 at 21 11 02@2x

**Comment by Noamko** [comment]
That's looking awesome!
I'll review it soon and open a PR to the store 💪🏼

**Comment by Noamko** [comment]
SVG format seems to not crop to the image itself causing the file to be much larger.
image

**Comment by marcjulianschwarz** [comment]
yes. I noticed this too. SVG was the main reason I wanted to implement all of the formats. Maybe there is a way to resize it in code. 
When you edit the SVG file you can  specify width and height but I don't think the API allows to specify these values.

**Comment by marcjulianschwarz** [comment]
We could use the [svgson package](https://www.npmjs.com/package/svgson) to get an editable SVG representation. Then edit width, height and the size of the viewbox. Then save it as a SVG file again.

So something like this 
```js

fs.readFile('path/to/your/file.svg', 'utf8', (err, data) => {

  svgson(data, (json) => {
    json.attributes.width = '500';
    json.attributes.height = '300';
    json.attributes.viewBox = '0 0 500 300';

    const modifiedSvg = svgson.stringify(json);
    fs.writeFile('path/to/your/modified/file.svg', modifiedSvg);
  });
});

```

We could allow the user to set these value in the extensions preferences.

**Comment by marcjulianschwarz** [comment]
There are now width, height and viewbox settings to adjust the look of the SVG image.

CleanShot 2023-09-13 at 22 12 08@2x

**Comment by marcjulianschwarz** [comment]
This goes beyond the scope of this pull request, but I really wanted to have a command argument, so here it is. It allows you to directly enter LaTeX without having to open the command.

CleanShot 2023-09-13 at 23 09 50

**Pull request merged**
